### ISSUE TITLE
User Colors

### ISSUE THREAD

**Issue by cookdoeyl** [bitfocus/companion-module-timemachines-clock#10]
Please add the ability to change the color to one of the 3 User defined colors.

**Comment by bryce-seifert** [comment]
I do not think this is currently possible with the TimeMachines API, or at least isn't [documented](https://www.timemachinescorp.com/wp-content/uploads/TimeMachinesControlAPI.pdf).

Seems like the color command requires RGB values
<img width="1474" alt="Screenshot 2023-12-30 at 2 49 54 PM" src="https://github.com/bitfocus/companion-module-timemachines-clock/assets/50299051/24c05247-a5b1-4473-8f48-d61216a696a3">

**Comment by cookdoeyl** [comment]
That would actually be way nicer. Being able to input RGB values from Companion. Right now, its just a drop down of the pre-defined. But if it can be individual RGB values off of 255, or using the Hex codes, that would be nice. No programming of the actual clock needed.

**Comment by bryce-seifert** [comment]
That makes a lot of sense.

I went ahead and added this, and it should be in the Companion betas by tomorrow. You will be able to select "Custom RGB" from the dropdown, and then enter your specific values.
